version: "2"
services:
    web:
        build:
            context: .
            dockerfile: container-build/web/dockerfile
        enviroment:
        - MYSQL_DATABASE=dbname
        - MYSQL_USER=dbuser
        - MYSQL_PASSWORD=password
        - MYSQL_HOST=db
        ports:
        - "8080:80"
        volumes:
        - .:/var/www
        depends_on:
        - db
        
    db:
        image: mysql:5.7
        ports: "6603:3306"
        enviroment:
        - MYSQL_ROOT_PASSWORD=Password
        - MYSQL_USER=db_user
        - MYSQL_PASSWORD=password
        - MYSQL_DATABASE=dbname
        volumes:
        - "mysql_data:/var/lib/mysql"
        - ./data/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
    mysql_data: { driver: local }            